// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAztbua2cKdeLCDE_-4q1mL0fSYpq7bRoQ',
    appId: '1:582543098521:web:65636fd29ad1c3b07a2e08',
    messagingSenderId: '582543098521',
    projectId: 'authentication-demo-8516c',
    authDomain: 'authentication-demo-8516c.firebaseapp.com',
    storageBucket: 'authentication-demo-8516c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARpfIHel84eBgel_coe4grmeFn4SGTs5s',
    appId: '1:582543098521:android:e557405ec577d3e47a2e08',
    messagingSenderId: '582543098521',
    projectId: 'authentication-demo-8516c',
    storageBucket: 'authentication-demo-8516c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALuvlErEbibGD5rdQ8GIK4UcKWm_YhEyQ',
    appId: '1:582543098521:ios:40e3e95fa7cbdd817a2e08',
    messagingSenderId: '582543098521',
    projectId: 'authentication-demo-8516c',
    storageBucket: 'authentication-demo-8516c.appspot.com',
    iosClientId: '582543098521-4uhg18rtk5r99kaek3b8u4gm6ogbl1ck.apps.googleusercontent.com',
    iosBundleId: 'com.example.tutorialApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALuvlErEbibGD5rdQ8GIK4UcKWm_YhEyQ',
    appId: '1:582543098521:ios:40e3e95fa7cbdd817a2e08',
    messagingSenderId: '582543098521',
    projectId: 'authentication-demo-8516c',
    storageBucket: 'authentication-demo-8516c.appspot.com',
    iosClientId: '582543098521-4uhg18rtk5r99kaek3b8u4gm6ogbl1ck.apps.googleusercontent.com',
    iosBundleId: 'com.example.tutorialApplication',
  );
}
